LANGUAGES = {"zh-TW": "繁體中文", "en": "English", "ja": "日本語"}
_language = "zh-TW"

def set_language(language):
    global _language
    _language = language if language in LANGUAGES else "zh-TW"

def tr(text):
    return TRANSLATIONS.get(text, {}).get(_language, text)

TRANSLATIONS = {
    '開啟紀錄資料夾': {'en': 'Open log folder', 'ja': 'ログフォルダーを開く'},
    '；紀錄：{0}': {'en': '; Log: {0}', 'ja': '；ログ：{0}'},
    '部分翻譯': {'en': 'Partially translated', 'ja': '翻訳未完了'},
    '{0} 張翻譯圖片｜部分翻譯': {'en': '{0} translated images | Incomplete', 'ja': '翻訳画像 {0} 枚｜翻訳未完了'},
    '清除搜尋': {'en': 'Clear search', 'ja': '検索をクリア'},
    '上次執行中斷，請確認結果後重試': {'en': 'The previous run was interrupted. Check its results before retrying.', 'ja': '前回の実行が中断されました。結果を確認してから再試行してください。'},
    '來源沒有可整合的圖片：{0}': {'en': 'Source has no images to merge: {0}', 'ja': '結合できる画像が元フォルダーにありません：{0}'},
    '章節範圍重疊或順序錯誤：{0}。請只選擇不重疊的來源章節。': {'en': 'Chapter ranges overlap or are out of order: {0}. Select only non-overlapping source chapters.', 'ja': '章の範囲が重複しているか順序が不正です：{0}。重複しない元の章のみ選択してください。'},
    '輸出已屬於其他來源，請改用不同的 Komga 路徑或系列名稱：{0}': {'en': 'Output belongs to another source. Use a different Komga path or series name: {0}', 'ja': '出力は別の元フォルダーに属しています。Komga の出力先またはシリーズ名を変更してください：{0}'},
    '\n\n既有輸出將被取代（包含其中的翻譯結果）：{0}': {'en': '\n\nExisting output will be replaced, including its translations: {0}', 'ja': '\n\n既存の出力は翻訳結果を含めて置き換えられます：{0}'},
    '\n\n注意：整合成功後，將永久刪除本次範圍內除最後一個之外的來源資料夾與內容。\n保留：{0}': {'en': '\n\nWarning: After a successful merge, all source folders and their contents in this range except the last folder will be permanently deleted.\nKeep: {0}', 'ja': '\n\n注意：結合が成功すると、今回の範囲内の最後のフォルダーを除くすべての元フォルダーとその内容が完全に削除されます。\n保持：{0}'},
    '\n已清除 {0} 個來源資料夾': {'en': '\nRemoved {0} source folders', 'ja': '\n元フォルダーを {0} 個削除しました'},
    '  清理：{0} 個資料夾／{1} 個項目': {'en': '  Cleanup: {0} folders / {1} items', 'ja': '  クリーンアップ：{0} 個のフォルダー／{1} 個の項目'},
    'BallonsTranslator 佇列': {'en': 'BallonsTranslator queue', 'ja': 'BallonsTranslator キュー'},
    'BallonsTranslator 未成功完成（exit={0}）；請查看其 logs': {'en': 'BallonsTranslator did not complete successfully (exit={0}); check its logs', 'ja': 'BallonsTranslator が正常に完了しませんでした（exit={0}）。ログを確認してください'},
    'BallonsTranslator 的 --exec_dirs 不支援含逗號的路徑': {'en': 'BallonsTranslator --exec_dirs does not support paths containing commas', 'ja': 'BallonsTranslator の --exec_dirs はカンマを含むパスに対応していません'},
    'BallonsTranslator：待命': {'en': 'BallonsTranslator: Standby', 'ja': 'BallonsTranslator：待機中'},
    'CBZ 內容損壞': {'en': 'Corrupted CBZ contents', 'ja': 'CBZ の内容が破損しています'},
    'CBZ 含有子資料夾或非圖片檔案': {'en': 'CBZ contains subfolders or non-image files', 'ja': 'CBZ にサブフォルダーまたは画像以外のファイルが含まれています'},
    'CBZ 圖片數量、順序或名稱不符': {'en': 'CBZ image count, order, or names do not match', 'ja': 'CBZ の画像数、順序、または名前が一致しません'},
    'Comic sorting 錯誤': {'en': 'Comic sorting error', 'ja': 'Comic sorting エラー'},
    'Komga 匯出': {'en': 'Komga export', 'ja': 'Komga エクスポート'},
    'Komga 匯出完成': {'en': 'Komga export complete', 'ja': 'Komga エクスポートが完了しました'},
    'Komga 匯出完成（含錯誤）': {'en': 'Komga export complete with errors', 'ja': 'Komga エクスポートが完了しました（一部エラーあり）'},
    'Komga 輸出路徑不能位於漫畫來源路徑內': {'en': 'Komga output path cannot be inside the comic source path', 'ja': 'Komga の出力先を漫画の元フォルダー内に指定することはできません'},
    'Komga 輸出路徑：': {'en': 'Komga output path:', 'ja': 'Komga 出力先：'},
    'Python（空白使用內附環境）': {'en': 'Python (blank = bundled)', 'ja': 'Python（空欄＝同梱環境）'},
    '{0}\n…共 {1} 個章節': {'en': '{0}\n…{1} chapters in total', 'ja': '{0}\n…全 {1} 章'},
    '{0} 個章節': {'en': '{0} chapters', 'ja': '{0} 章'},
    '{0} 個系列，{1} 個章節': {'en': '{0} series, {1} chapters', 'ja': '{0} シリーズ、{1} 章'},
    '{0} 張圖片｜未翻譯': {'en': '{0} images | Untranslated', 'ja': '画像 {0} 枚｜未翻訳'},
    '{0} 張翻譯圖片｜可匯出': {'en': '{0} translated images | Ready to export', 'ja': '翻訳済み画像 {0} 枚｜エクスポート可能'},
    '{0}: 不清理符號連結': {'en': '{0}: Skipping symlink cleanup', 'ja': '{0}：シンボリックリンクは削除しません'},
    '一鍵整合＋主佇列': {'en': 'Merge + main queue', 'ja': '一括結合＋メインキュー'},
    '不允許刪除系列目錄外或符號連結資料夾': {'en': 'Cannot delete folders outside the series directory or symlink folders', 'ja': 'シリーズのディレクトリ外にあるフォルダーやシンボリックリンクのフォルダーは削除できません'},
    '主佇列進度': {'en': 'Main queue progress', 'ja': 'メインキューの進行状況'},
    '佇列將清空指定路徑的 mask / inpainted 內容，無法復原。繼續？': {'en': 'The queue will clear mask / inpainted contents at the specified paths. This cannot be undone. Continue?', 'ja': 'キューは指定パスの mask / inpainted の内容を削除します。この操作は元に戻せません。続行しますか？'},
    '佇列已停止': {'en': 'Queue stopped', 'ja': 'キューを停止しました'},
    '佇列結束，請查看各項狀態': {'en': 'Queue finished. Check the status of each item', 'ja': 'キューの処理が終了しました。各項目の状態を確認してください'},
    '佇列設定': {'en': 'Queue settings', 'ja': 'キュー設定'},
    '來源不是資料夾': {'en': 'Source is not a folder', 'ja': '元のパスがフォルダーではありません'},
    '來源清理失敗': {'en': 'Source cleanup failed', 'ja': '元フォルダーの削除に失敗しました'},
    '停止': {'en': 'Stop', 'ja': '停止'},
    '加入上方選取項目': {'en': 'Add items selected above', 'ja': '上で選択した項目を追加'},
    '加入指定路徑': {'en': 'Add path', 'ja': 'パスを指定して追加'},
    '動作': {'en': 'Action', 'ja': '操作'},
    '匯出': {'en': 'Export', 'ja': 'エクスポート'},
    '匯出完成後開啟輸出資料夾': {'en': 'Open output folder after export', 'ja': 'エクスポート後に出力フォルダーを開く'},
    '匯出所有已翻譯項目': {'en': 'Export all translated items', 'ja': '翻訳済みの全項目をエクスポート'},
    '匯出與漫畫路徑不可互相包含': {'en': 'Export and comic paths cannot contain each other', 'ja': '出力先と漫画のパスを互いの配下に指定することはできません'},
    '匯出選取項目': {'en': 'Export selected items', 'ja': '選択項目をエクスポート'},
    '可匯出': {'en': 'Ready to export', 'ja': 'エクスポート可能'},
    '執行中': {'en': 'Running', 'ja': '実行中'},
    '失敗': {'en': 'Failed', 'ja': '失敗'},
    '失敗：{0}': {'en': 'Failed: {0}', 'ja': '失敗：{0}'},
    '安裝路徑': {'en': 'Installation path', 'ja': 'インストール先'},
    '完成': {'en': 'Complete', 'ja': '完了'},
    '將清空目前漫畫路徑下所有 mask 與 inpainted 資料夾內容。\n資料夾本身會保留，此操作無法復原。確定繼續嗎？': {'en': 'This will clear all mask and inpainted folder contents under the current comic path.\nThe folders themselves will be kept. This cannot be undone. Continue?', 'ja': '現在の漫画パス内にあるすべての mask と inpainted フォルダーの内容を削除します。\nフォルダー自体は残ります。この操作は元に戻せません。続行しますか？'},
    '尚未掃描': {'en': 'Not scanned yet', 'ja': '未スキャン'},
    '就緒': {'en': 'Ready', 'ja': '準備完了'},
    '工作執行中': {'en': 'Task running', 'ja': 'タスク実行中'},
    '已停止': {'en': 'Stopped', 'ja': '停止しました'},
    '已停止，未執行後續清理': {'en': 'Stopped; subsequent cleanup was not performed', 'ja': '停止しました。後続のクリーンアップは実行されていません'},
    '已停止；未執行此項目的後續動作': {'en': 'Stopped; subsequent actions for this item were not performed', 'ja': '停止しました。この項目の後続処理は実行されていません'},
    '已存在且來源未變更時跳過': {'en': 'Skip existing items if the source is unchanged', 'ja': '元データに変更がない既存項目をスキップ'},
    '已清理 {0} 個資料夾、移除 {1} 個項目': {'en': 'Cleaned {0} folders and removed {1} items', 'ja': '{0} 個のフォルダーをクリーンアップし、{1} 個の項目を削除しました'},
    '序號｜系列 / 章節': {'en': 'No. | Series / Chapter', 'ja': '番号｜シリーズ／章'},
    '您確定要整合以下資料夾嗎？\n\n{0}': {'en': 'Merge the following folders?\n\n{0}', 'ja': '次のフォルダーを結合しますか？\n\n{0}'},
    '成功後清理 mask / inpainted': {'en': 'Clean up mask / inpainted on success', 'ja': '成功後に mask / inpainted をクリーンアップ'},
    '指定路徑沒有圖片，請選擇章節或整合輸出': {'en': 'No images at the specified path. Select a chapter or merge output', 'ja': '指定パスに画像がありません。章または結合結果を選択してください'},
    '掃描失敗': {'en': 'Scan failed', 'ja': 'スキャンに失敗しました'},
    '整合失敗': {'en': 'Merge failed', 'ja': '結合に失敗しました'},
    '整合完成（清理含錯誤）': {'en': 'Merge complete with cleanup errors', 'ja': '結合が完了しました（クリーンアップでエラーあり）'},
    '整合後清除來源（保留最後一個）': {'en': 'Delete sources after merging (keep the last folder)', 'ja': '結合後に元フォルダーを削除（最後のフォルダーは保持）'},
    '新增': {'en': 'New', 'ja': '新規'},
    '新增：{0}  更新：{1}  跳過：{2}  失敗：{3}': {'en': 'New: {0}  Updated: {1}  Skipped: {2}  Failed: {3}', 'ja': '新規：{0}  更新：{1}  スキップ：{2}  失敗：{3}'},
    '更新': {'en': 'Update', 'ja': '更新'},
    '更新時間 ↓': {'en': 'Modified ↓', 'ja': '更新日時 ↓'},
    '未翻譯': {'en': 'Untranslated', 'ja': '未翻訳'},
    '檔案已重命名並複製到 {0}': {'en': 'Files renamed and copied to {0}', 'ja': 'ファイル名を変更し、{0} にコピーしました'},
    '正在掃描…': {'en': 'Scanning…', 'ja': 'スキャン中…'},
    '正在整合… {0} / {1}': {'en': 'Merging… {0} / {1}', 'ja': '結合中… {0} / {1}'},
    '正在清理 mask / inpainted…': {'en': 'Cleaning up mask / inpainted…', 'ja': 'mask / inpainted をクリーンアップ中…'},
    '正在處理：{0}': {'en': 'Processing: {0}', 'ja': '処理中：{0}'},
    '正在處理：{0} — {1} / {2}': {'en': 'Processing: {0} — {1} / {2}', 'ja': '処理中：{0} — {1} / {2}'},
    '此路徑前置工作失敗，跳過後續動作': {'en': 'A prerequisite task failed for this path; skipping subsequent actions', 'ja': 'このパスの前段階の処理に失敗したため、後続処理をスキップします'},
    '沒有可匯出的翻譯結果': {'en': 'No translated results available to export', 'ja': 'エクスポート可能な翻訳結果がありません'},
    '清理': {'en': 'Cleanup', 'ja': 'クリーンアップ'},
    '清理失敗': {'en': 'Cleanup failed', 'ja': 'クリーンアップに失敗しました'},
    '清理失敗：{0}': {'en': 'Cleanup failed: {0}', 'ja': 'クリーンアップに失敗しました：{0}'},
    '清理完成': {'en': 'Cleanup complete', 'ja': 'クリーンアップが完了しました'},
    '清理完成（含錯誤）': {'en': 'Cleanup complete with errors', 'ja': 'クリーンアップが完了しました（一部エラーあり）'},
    '清理所有 mask / inpainted': {'en': 'Clean up all mask / inpainted folders', 'ja': 'すべての mask / inpainted をクリーンアップ'},
    '準備匯出…': {'en': 'Preparing export…', 'ja': 'エクスポートを準備中…'},
    '準備整合…': {'en': 'Preparing merge…', 'ja': '結合を準備中…'},
    '漫畫整合': {'en': 'Comic merge', 'ja': '漫画の結合'},
    '漫畫整合工具': {'en': 'Comic merge tool', 'ja': '漫画結合ツール'},
    '漫畫路徑': {'en': 'Comic path', 'ja': '漫画パス'},
    '漫畫路徑不存在': {'en': 'Comic path does not exist', 'ja': '漫画パスが存在しません'},
    '漫畫路徑：': {'en': 'Comic path:', 'ja': '漫画パス：'},
    '瀏覽': {'en': 'Browse', 'ja': '参照'},
    '無法寫入 EXE 同目錄的設定檔：\n{0}\n\n{1}': {'en': 'Cannot write the settings file in the EXE directory:\n{0}\n\n{1}', 'ja': 'EXE と同じディレクトリに設定ファイルを書き込めません：\n{0}\n\n{1}'},
    '狀態': {'en': 'Status', 'ja': '状態'},
    '狀態檔: {0}': {'en': 'Status file: {0}', 'ja': '状態ファイル：{0}'},
    '確認整合': {'en': 'Confirm merge', 'ja': '結合の確認'},
    '確認清理': {'en': 'Confirm cleanup', 'ja': 'クリーンアップの確認'},
    '移除選取': {'en': 'Remove selected', 'ja': '選択項目を削除'},
    '等待': {'en': 'Waiting', 'ja': '待機中'},
    '結束編號：': {'en': 'End number:', 'ja': '終了番号：'},
    '結果為空': {'en': 'Empty result', 'ja': '結果が空です'},
    '結果資料夾為空': {'en': 'Result folder is empty', 'ja': '結果フォルダーが空です'},
    '翻譯': {'en': 'Translate', 'ja': '翻訳'},
    '翻譯成功後匯出 CBZ': {'en': 'Export CBZ after successful translation', 'ja': '翻訳成功後に CBZ をエクスポート'},
    '翻譯結果不完整，未執行後續動作': {'en': 'Translation results are incomplete; subsequent actions were not performed', 'ja': '翻訳結果が不完全なため、後続処理は実行されていません'},
    '設定保存失敗': {'en': 'Failed to save settings', 'ja': '設定の保存に失敗しました'},
    '請先在 BallonsTranslator 儲存設定並關閉原生介面': {'en': 'Save settings in BallonsTranslator and close its interface first', 'ja': '先に BallonsTranslator で設定を保存し、その画面を閉じてください'},
    '請先選擇父系列或章節': {'en': 'Select a parent series or chapter first', 'ja': '先に親シリーズまたは章を選択してください'},
    '請確保編號範圍有效': {'en': 'Make sure the number range is valid', 'ja': '番号の範囲が正しいか確認してください'},
    '請確認漫畫與 Komga 路徑': {'en': 'Check the comic and Komga paths', 'ja': '漫画と Komga のパスを確認してください'},
    '請等待目前工作完成，或先停止翻譯佇列。': {'en': 'Wait for the current task to finish, or stop the translation queue first.', 'ja': '現在のタスクが完了するまで待つか、先に翻訳キューを停止してください。'},
    '請設定 Komga 輸出路徑': {'en': 'Set the Komga output path', 'ja': 'Komga の出力先を設定してください'},
    '請設定有效的 BallonsTranslator 安裝目錄及其 Python 執行檔': {'en': 'Set a valid BallonsTranslator installation directory and its Python executable', 'ja': '有効な BallonsTranslator のインストール先と、その Python 実行ファイルを設定してください'},
    '請輸入有效的起始和結束編號': {'en': 'Enter valid start and end numbers', 'ja': '有効な開始番号と終了番号を入力してください'},
    '請選擇既有 BallonsTranslator config JSON': {'en': 'Select an existing BallonsTranslator config JSON', 'ja': '既存の BallonsTranslator 設定 JSON を選択してください'},
    '請選擇有效的漫畫路徑': {'en': 'Select a valid comic path', 'ja': '有効な漫画パスを選択してください'},
    '警告': {'en': 'Warning', 'ja': '警告'},
    '資料夾大小': {'en': 'Folder size', 'ja': 'フォルダーサイズ'},
    '起始編號：': {'en': 'Start number:', 'ja': '開始番号：'},
    '跳過': {'en': 'Skip', 'ja': 'スキップ'},
    '輸出路徑不是資料夾：{0}': {'en': 'Output path is not a folder: {0}', 'ja': '出力先がフォルダーではありません：{0}'},
    '選取範圍沒有可整合的圖片': {'en': 'No images to merge in the selected range', 'ja': '選択範囲に結合可能な画像がありません'},
    '選取項目沒有可匯出的翻譯結果': {'en': 'No translated results to export in the selected items', 'ja': '選択項目にエクスポート可能な翻訳結果がありません'},
    '重新掃描': {'en': 'Rescan', 'ja': '再スキャン'},
    '開啟原生設定介面': {'en': 'Open native settings interface', 'ja': '本体の設定画面を開く'},
    '開始主佇列': {'en': 'Start main queue', 'ja': 'メインキューを開始'},
    '重新啟動後套用語言': {'en': 'Language changes take effect after restart', 'ja': '言語の変更は再起動後に適用されます'},
    '設定檔': {'en': 'Config file', 'ja': '設定ファイル'},
    'Text Detection': {'zh-TW': '文字偵測', 'en': 'Text Detection', 'ja': '文字検出'},
    'OCR': {'zh-TW': 'OCR', 'en': 'OCR', 'ja': 'OCR'},
    'Translation': {'zh-TW': '翻譯', 'en': 'Translation', 'ja': '翻訳'},
    'Inpaint': {'zh-TW': '修補', 'en': 'Inpaint', 'ja': '画像修復'},
}

TRANSLATIONS.update({
    "搜尋系列／章節": {"en": "Search series / chapters", "ja": "シリーズ／章を検索"},
    "已選取 {0} 個章節": {"en": "{0} chapters selected", "ja": "{0} 章を選択中"},
    "主佇列": {"en": "Queue", "ja": "キュー"},
    "設定": {"en": "Settings", "ja": "設定"},
    "整合時請只選擇同一系列的章節": {"en": "Select chapters from one series to merge", "ja": "結合する章は同じシリーズから選択してください"},
    "前置工作失敗": {"en": "Blocked", "ja": "前の処理が失敗"},
    "上移": {"en": "Move up", "ja": "上へ"},
    "下移": {"en": "Move down", "ja": "下へ"},
    "重試選取": {"en": "Retry selected", "ja": "選択項目を再試行"},
    "清除已完成": {"en": "Clear completed", "ja": "完了項目を除去"},
    "工作詳情": {"en": "Job details", "ja": "処理の詳細"},
    "佇列 {0} 項｜等待 {1}｜完成 {2}｜需處理 {3}": {"en": "Queue: {0} | Pending: {1} | Done: {2} | Needs attention: {3}", "ja": "キュー {0} 件｜待機 {1}｜完了 {2}｜要確認 {3}"},
    "不支援的佇列動作：{0}": {"en": "Unsupported queue action: {0}", "ja": "未対応のキュー操作：{0}"},
    "請先重試此路徑的失敗工作：{0}": {"en": "Retry the failed job for this path first: {0}", "ja": "このパスで失敗した処理を先に再試行してください：{0}"},
})
