LANGUAGES = {"zh-TW": "繁體中文", "en": "English", "ja": "日本語"}
_language = "zh-TW"

def set_language(language):
    global _language
    _language = language if language in LANGUAGES else "zh-TW"

def tr(text):
    return TRANSLATIONS.get(text, {}).get(_language, text)

TRANSLATIONS = {
    'ntfy 通知': {'en': 'ntfy notifications', 'ja': 'ntfy 通知'},
    '通知設定欄位必須是文字': {'en': 'Notification settings must be text', 'ja': '通知設定の欄は文字列で指定してください'},
    '通知背景程序無法啟動': {'en': 'Cannot start notification worker', 'ja': '通知のバックグラウンド処理を開始できません'},
    'ntfy 權杖無效或未提供': {'en': 'ntfy token invalid or missing', 'ja': 'ntfy トークンが無効または未指定です'},
    '伺服器拒絕請求（HTTP 403）；請檢查 ntfy 權限或代理／防火牆規則': {'en': 'Request rejected (HTTP 403); check ntfy permissions or proxy/firewall rules', 'ja': 'リクエストが拒否されました（HTTP 403）。ntfy の権限やプロキシ／ファイアウォールの設定を確認してください'},
    'Cloudflare 阻擋用戶端（1010）；請檢查伺服器的 Cloudflare 規則，並非 ntfy 權杖權限判定': {'en': 'Cloudflare blocked the client (1010); check the server’s Cloudflare rules. This is not an ntfy token permission result', 'ja': 'Cloudflare がクライアントをブロックしました（1010）。サーバーの Cloudflare ルールを確認してください。ntfy のトークン権限の判定ではありません'},
    'ntfy 伺服器網址不存在': {'en': 'ntfy server URL not found', 'ja': 'ntfy サーバー URL が見つかりません'},
    'ntfy 通知頻率或額度已達上限': {'en': 'ntfy rate or quota limit reached', 'ja': 'ntfy の送信頻度または利用枠の上限に達しました'},
    'ntfy 連線失敗或逾時；為避免重複通知，未自動重送': {'en': 'ntfy connection failed or timed out; not resent to avoid duplicate notifications', 'ja': 'ntfy 接続失敗またはタイムアウト。重複通知を避けるため再送していません'},
    '伺服器未回傳有效的 ntfy 發布結果': {'en': 'Server did not return a valid ntfy publish result', 'ja': 'サーバーが有効な ntfy 送信結果を返しませんでした'},
    '啟用通知': {'en': 'Enable notifications', 'ja': '通知を有効にする'},
    '整批結束': {'en': 'Queue finished', 'ja': 'キュー終了'},
    '單項失敗／異常': {'en': 'Job failed / warning', 'ja': 'ジョブ失敗／異常'},
    '單項成功': {'en': 'Job succeeded', 'ja': 'ジョブ成功'},
    '伺服器網址': {'en': 'Server URL', 'ja': 'サーバー URL'},
    '主題（Topic）': {'en': 'Topic', 'ja': 'トピック'},
    '存取權杖（選填）': {'en': 'Access token (optional)', 'ja': 'アクセストークン（任意）'},
    '儲存通知設定': {'en': 'Save notification settings', 'ja': '通知設定を保存'},
    '測試通知': {'en': 'Test notification', 'ja': 'テスト通知'},
    '複製訂閱網址': {'en': 'Copy subscription URL', 'ja': '購読 URL をコピー'},
    '通知設定已儲存': {'en': 'Notification settings saved', 'ja': '通知設定を保存しました'},
    '通知設定儲存失敗': {'en': 'Failed to save notification settings', 'ja': '通知設定の保存に失敗しました'},
    '訂閱網址已複製；請在其他設備訂閱': {'en': 'Subscription URL copied; subscribe on your other devices', 'ja': '購読 URL をコピーしました。他の端末で購読してください'},
    '尚未發送通知': {'en': 'No notifications sent yet', 'ja': 'まだ通知を送信していません'},
    '通知發送中…': {'en': 'Sending notification…', 'ja': '通知を送信中…'},
    'ntfy 連線測試成功，這是 Comic sorting 的測試通知。': {'en': 'ntfy connection test succeeded. This is a Comic sorting test notification.', 'ja': 'ntfy 接続テストが成功しました。Comic sorting のテスト通知です。'},
    '手機／其他設備訂閱相同伺服器與主題；公開主題請勿分享，權杖需搭配受保護主題。': {'en': 'Subscribe to the same server/topic on your devices. Keep public topics private; tokens require protected topics.', 'ja': '各端末で同じサーバーとトピックを購読してください。公開トピック名は共有せず、トークンには保護されたトピックを使用してください。'},
    '請輸入 ntfy 伺服器網址，例如 https://ntfy.sh（不含主題或查詢參數）': {'en': 'Enter an ntfy server URL such as https://ntfy.sh (without a topic or query parameters)', 'ja': 'https://ntfy.sh などの ntfy サーバー URL を入力してください（トピックやクエリは含めません）'},
    '主題須為 1–64 個英文字母、數字、底線或連字號': {'en': 'Topic must contain 1–64 ASCII letters, digits, underscores or hyphens', 'ja': 'トピックは半角英数字、アンダースコア、ハイフンの 1～64 文字で指定してください'},
    '存取權杖須使用 HTTPS，且不可包含空白或換行': {'en': 'Access tokens require HTTPS and cannot contain whitespace or line breaks', 'ja': 'トークンには HTTPS が必要です。空白や改行は使用できません'},
    '權杖無法解密，請重新輸入並儲存；通知尚未發送': {'en': 'Cannot decrypt token; re-enter and save it. No notification was sent', 'ja': 'トークンを復号できません。再入力して保存してください。通知は送信していません'},
    '權杖保護失敗，設定未儲存': {'en': 'Token protection failed; settings were not saved', 'ja': 'トークンの保護に失敗しました。設定は保存していません'},
    '通知等待過多，已略過本則通知': {'en': 'Too many pending notifications; this notification was skipped', 'ja': '待機中の通知が多すぎるため、この通知を省略しました'},
    '通知已送達 ntfy 伺服器；設備需開啟通知權限': {'en': 'Notification accepted by ntfy; enable notifications on your devices', 'ja': 'ntfy が通知を受信しました。端末の通知権限を有効にしてください'},
    '通知未確認送達；請檢查網址、訂閱、權限或網路，翻譯佇列不受影響': {'en': 'Delivery not confirmed; check URL, subscription, permissions or network. Translation is unaffected', 'ja': '配信を確認できません。URL、購読、権限、ネットワークを確認してください。翻訳には影響しません'},
    '預估金額非實際帳單；僅含已回報用量。': {'en': 'Estimated cost is not a bill; includes reported usage only.', 'ja': '推定金額は実際の請求額ではありません。報告された使用量のみを含みます。'},
    '完成時間：{0}': {'en': 'Finished at: {0}', 'ja': '終了時刻：{0}'},
    '開始時間：{0}': {'en': 'Started at: {0}', 'ja': '開始時刻：{0}'},
    '完成 {0}｜異常 {1}｜失敗 {2}｜略過 {3}｜停止 {4}｜未執行 {5}': {'en': 'Done {0} | Warnings {1} | Failed {2} | Skipped {3} | Stopped {4} | Not run {5}', 'ja': '完了 {0}｜異常 {1}｜失敗 {2}｜省略 {3}｜停止 {4}｜未実行 {5}'},
    '錯誤碼': {'en': 'Error code', 'ja': 'エラーコード'},
    '錯誤原因': {'en': 'Error reason', 'ja': 'エラー原因'},
    '原始訊息': {'en': 'Original message', 'ja': '元のメッセージ'},
    '模型服務暫時滿載': {'en': 'Model service is temporarily at capacity', 'ja': 'モデルサービスが一時的に混雑しています'},
    '帳號額度、餘額或支出上限不足': {'en': 'Account quota, credits or spending limit exhausted', 'ja': '利用枠、残高または支出上限に達しました'},
    '登入已失效或 API 金鑰無效／未設定': {'en': 'Login expired or API key invalid/missing', 'ja': 'ログインの期限切れ、または API キーが無効／未設定です'},
    '模型未設定、不存在或不可用': {'en': 'Model missing, not found or unavailable', 'ja': 'モデルが未設定、存在しない、または利用できません'},
    '服務網址或請求設定無效': {'en': 'Invalid service URL or request settings', 'ja': 'サービス URL またはリクエスト設定が無効です'},
    '輸入超過模型上下文上限': {'en': 'Input exceeds the model context limit', 'ja': '入力がモデルのコンテキスト上限を超えています'},
    '模型輸出達到 Token 上限': {'en': 'Model output reached the token limit', 'ja': 'モデル出力がトークン上限に達しました'},
    '服務拒絕處理此內容': {'en': 'Service refused to process this content', 'ja': 'サービスがこの内容の処理を拒否しました'},
    'Codex 執行檔不存在或無法啟動': {'en': 'Codex executable missing or failed to start', 'ja': 'Codex 実行ファイルが見つからないか、起動できません'},
    'Codex 要求互動操作，無法自動繼續': {'en': 'Codex requires interaction and cannot continue automatically', 'ja': 'Codex が対話操作を要求したため、自動で続行できません'},
    'Codex 回應格式或通訊協定異常': {'en': 'Invalid Codex response format or protocol', 'ja': 'Codex の応答形式または通信プロトコルに異常があります'},
    'Codex 子程序提前結束': {'en': 'Codex subprocess exited before completion', 'ja': 'Codex の子プロセスが完了前に終了しました'},
    '等待服務回應逾時': {'en': 'Timed out waiting for the service', 'ja': 'サービス応答の待機がタイムアウトしました'},
    '網路、代理伺服器或 TLS 連線失敗': {'en': 'Network, proxy or TLS connection failed', 'ja': 'ネットワーク、プロキシまたは TLS 接続に失敗しました'},
    '請求頻率過高，服務已限流': {'en': 'Service rate limit reached', 'ja': 'リクエスト頻度がサービスの制限に達しました'},
    '服務拒絕存取，帳號或地區權限不足': {'en': 'Service access denied by account or region restrictions', 'ja': 'アカウントまたは地域の制限によりアクセスが拒否されました'},
    'GPU 顯示記憶體不足': {'en': 'GPU memory exhausted', 'ja': 'GPU メモリが不足しています'},
    '系統記憶體不足': {'en': 'System memory exhausted', 'ja': 'システムメモリが不足しています'},
    'Python 套件或 DLL 載入失敗': {'en': 'Python package or DLL failed to load', 'ja': 'Python パッケージまたは DLL の読み込みに失敗しました'},
    '圖片損壞、格式不支援或無法讀取': {'en': 'Image damaged, unsupported or unreadable', 'ja': '画像が破損、未対応、または読み取れません'},
    '磁碟空間不足': {'en': 'Disk space exhausted', 'ja': 'ディスクの空き容量が不足しています'},
    '檔案正在被其他程式使用': {'en': 'File is in use by another process', 'ja': 'ファイルは他のプロセスで使用中です'},
    '檔案存取權限不足': {'en': 'File access permission denied', 'ja': 'ファイルへのアクセス権限がありません'},
    '檔案或資料夾不存在': {'en': 'File or folder does not exist', 'ja': 'ファイルまたはフォルダーが存在しません'},
    '檔案路徑超過系統限制': {'en': 'File path exceeds the system limit', 'ja': 'ファイルパスがシステムの上限を超えています'},
    '翻譯摘要記憶整理失敗': {'en': 'Translation summary memory compaction failed', 'ja': '翻訳要約メモリの整理に失敗しました'},
    '模型回覆格式、翻譯數量或內容不符合要求': {'en': 'Model response format, translation count or content is invalid', 'ja': 'モデル応答の形式、翻訳数または内容が不正です'},
    '文字偵測模組執行失敗': {'en': 'Text detection module failed', 'ja': '文字検出モジュールが失敗しました'},
    'OCR 模組執行失敗': {'en': 'OCR module failed', 'ja': 'OCR モジュールが失敗しました'},
    '修補模組執行失敗': {'en': 'Inpainting module failed', 'ja': '修復モジュールが失敗しました'},
    '翻譯程序異常終止': {'en': 'Translation process crashed', 'ja': '翻訳プロセスが異常終了しました'},
    'BallonsTranslator 安裝路徑或 Python 無效': {'en': 'Invalid BallonsTranslator installation or Python', 'ja': 'BallonsTranslator のインストール先または Python が無効です'},
    '設定檔或專案 JSON 無法讀取': {'en': 'Configuration or project JSON cannot be read', 'ja': '設定またはプロジェクトの JSON を読み込めません'},
    '漫畫資料夾不存在': {'en': 'Comic folder does not exist', 'ja': '漫画フォルダーが存在しません'},
    '資料夾內沒有可處理的圖片': {'en': 'No processable images in the folder', 'ja': 'フォルダーに処理できる画像がありません'},
    '翻譯頁數範圍無效或頁面已不存在': {'en': 'Invalid page range or pages no longer exist', 'ja': 'ページ範囲が無効、またはページが存在しません'},
    '未啟用任何處理階段': {'en': 'No processing stage is enabled', 'ja': '処理工程が有効になっていません'},
    '翻譯結果不完整，已略過後續動作': {'en': 'Translation incomplete; follow-up actions skipped', 'ja': '翻訳結果が不完全なため、後続処理を省略しました'},
    '匯出路徑未設定、互相包含或已被其他來源使用': {'en': 'Export path missing, overlapping or used by another source', 'ja': '出力先が未設定、包含関係にある、または別の入力に使用されています'},
    'CBZ 壓縮檔驗證失敗': {'en': 'CBZ archive validation failed', 'ja': 'CBZ アーカイブの検証に失敗しました'},
    '操作路徑或符號連結不符合限制': {'en': 'Path or symbolic link violates operation constraints', 'ja': 'パスまたはシンボリックリンクが操作の制限に違反しています'},
    '服務回報 429；需查看原始訊息確認頻率或額度限制': {'en': 'Service returned 429; inspect the original rate/quota error', 'ja': '429 応答です。頻度制限か利用枠かは元のメッセージを確認してください'},
    '服務拒絕請求，請查看原始 HTTP 錯誤': {'en': 'Service rejected the request; inspect the HTTP error', 'ja': 'サービスがリクエストを拒否しました。元の HTTP エラーを確認してください'},
    '遠端服務或閘道發生錯誤': {'en': 'Remote service or gateway error', 'ja': 'リモートサービスまたはゲートウェイのエラーです'},
    '請求參數無效或不受支援': {'en': 'Request parameters invalid or unsupported', 'ja': 'リクエストパラメーターが無効、または未対応です'},
    'BallonsTranslator 版本不支援此功能': {'en': 'BallonsTranslator version does not support this feature', 'ja': 'この BallonsTranslator バージョンは機能に対応していません'},
    '翻譯流程提前停止，未回報更明確原因': {'en': 'Translation stopped early without a more specific cause', 'ja': '詳細な原因が報告されないまま翻訳が中止されました'},
    '翻譯程序以非零代碼結束': {'en': 'Translation process returned a nonzero exit code', 'ja': '翻訳プロセスがゼロ以外の終了コードを返しました'},
    '翻譯程序未完成所有階段': {'en': 'Translation process did not complete all stages', 'ja': '翻訳プロセスがすべての工程を完了しませんでした'},
    '同一資料夾的前置工作失敗，已略過此項': {'en': 'Skipped because a predecessor for this folder failed', 'ja': '同じフォルダーの前提処理が失敗したため、省略しました'},
    '上次執行中斷，需確認成果後重試': {'en': 'Previous run interrupted; check results before retrying', 'ja': '前回の実行が中断されました。結果を確認して再試行してください'},
    '使用者或主佇列要求停止': {'en': 'Stop requested by the user or main queue', 'ja': 'ユーザーまたはメインキューが停止を要求しました'},
    '未能分類的錯誤，請查看原始訊息': {'en': 'Unclassified error; inspect the original message', 'ja': '未分類のエラーです。元のメッセージを確認してください'},
    '流程完成但有異常，請查看原始訊息': {'en': 'Completed with anomalies; inspect the original message', 'ja': '異常を伴って完了しました。元のメッセージを確認してください'},
    '歷史紀錄': {'en': 'History', 'ja': '履歴'},
    '估價依據：{0}（費率日期：{1}）': {'en': 'Estimate basis: {0} (rates date: {1})', 'ja': '推定根拠：{0}（料金基準日：{1}）'},
    '漫畫名稱／路徑': {'en': 'Comic name / path', 'ja': '漫画名／パス'},
    '開始日期': {'en': 'From date', 'ja': '開始日'},
    '結束日期': {'en': 'To date', 'ja': '終了日'},
    '查詢／重新整理': {'en': 'Search / Refresh', 'ja': '検索／更新'},
    '開始時間': {'en': 'Started at', 'ja': '開始日時'},
    '開始時間／資料夾': {'en': 'Started at / Folder', 'ja': '開始日時／フォルダー'},
    '本次佇列累計': {'en': 'Queue totals', 'ja': '今回のキューの合計'},
    '完成時間': {'en': 'Finished at', 'ja': '終了日時'},
    '最後儲存時間': {'en': 'Last saved', 'ja': '最終保存日時'},
    '工作數': {'en': 'Jobs', 'ja': '件数'},
    '耗時': {'en': 'Duration', 'ja': '所要時間'},
    '合計用量／預估金額': {'en': 'Total usage / estimated cost', 'ja': '合計使用量／推定金額'},
    '未結束': {'en': 'Not finished', 'ja': '未終了'},
    '階段耗時可能重疊；金額為估算，僅包含已回報用量。': {'en': 'Stage times may overlap; costs are estimates and include reported usage only.', 'ja': '工程時間は重複する場合があります。金額は報告済み使用量のみの推定です。'},
    '顯示 {0} 筆（最多 200 筆）；日期格式 YYYY-MM-DD，留白不限。展開佇列及資料夾查看用量，選取後查看詳細資料。': {'en': 'Showing {0} records (up to 200). Dates: YYYY-MM-DD; leave blank for no limit. Expand queues and folders for usage; select a row for details.', 'ja': '{0} 件を表示（最大 200 件）。日付は YYYY-MM-DD、空欄は制限なし。キューとフォルダーを展開すると使用量を、選択すると詳細を表示します。'},
    '日期請使用 YYYY-MM-DD 格式': {'en': 'Use YYYY-MM-DD for dates', 'ja': '日付は YYYY-MM-DD 形式で入力してください'},
    '結束日期不可早於開始日期': {'en': 'End date cannot precede start date', 'ja': '終了日を開始日より前にすることはできません'},
    '歷史紀錄讀取失敗': {'en': 'Could not read history', 'ja': '履歴の読み込みに失敗'},
    '歷史紀錄儲存失敗': {'en': 'Could not save history', 'ja': '履歴の保存に失敗'},
    '已要求停止佇列；請檢查歷史檔寫入權限及磁碟空間後重試。\n{0}\n\n{1}': {'en': 'The queue has been asked to stop. Check history file permissions and disk space, then retry.\n{0}\n\n{1}', 'ja': 'キューの停止を要求しました。履歴ファイルの書き込み権限と空き容量を確認して再試行してください。\n{0}\n\n{1}'},
    '完成後開啟資料夾': {'en': 'Open folder when finished', 'ja': '完了後にフォルダーを開く'},
    '刪除章節資料夾…': {'en': 'Delete chapter folder…', 'ja': '章フォルダーを削除…'},
    '刪除系列資料夾…': {'en': 'Delete series folder…', 'ja': 'シリーズフォルダーを削除…'},
    '確認移至資源回收筒': {'en': 'Confirm move to Recycle Bin', 'ja': 'ごみ箱への移動を確認'},
    '整個系列及其下所有章節（包含搜尋未顯示的章節）': {'en': 'The entire series and all its chapters (including chapters hidden by search)', 'ja': 'シリーズ全体とすべての章（検索で非表示の章も含む）'},
    '此章節及其所有檔案': {'en': 'This chapter and all its files', 'ja': 'この章とその中のすべてのファイル'},
    '將移至資源回收筒：\n{0}\n\n範圍：{1}\n成功後才會移除相關佇列項目。\n可至資源回收筒還原。確定繼續嗎？': {'en': 'Move to Recycle Bin:\n{0}\n\nScope: {1}\nRelated queue items will be removed only after success.\nYou can restore the folder from the Recycle Bin. Continue?', 'ja': 'ごみ箱へ移動します：\n{0}\n\n対象：{1}\n成功した場合のみ関連するキュー項目を削除します。\nごみ箱から復元できます。続行しますか？'},
    '正在移至資源回收筒：{0}': {'en': 'Moving to Recycle Bin: {0}', 'ja': 'ごみ箱へ移動中：{0}'},
    '已移至資源回收筒：{0}': {'en': 'Moved to Recycle Bin: {0}', 'ja': 'ごみ箱へ移動済み：{0}'},
    '移至資源回收筒失敗': {'en': 'Move to Recycle Bin failed', 'ja': 'ごみ箱への移動に失敗'},
    '無法移至資源回收筒，已停止刪除': {'en': 'Cannot move to Recycle Bin; deletion stopped', 'ja': 'ごみ箱に移動できないため、削除を中止しました'},
    '只能刪除漫畫路徑內的系列或章節，不能刪除漫畫根目錄': {'en': 'Only series or chapters inside the manga path can be deleted, not the manga root itself', 'ja': '漫画パス内のシリーズまたは章のみ削除できます。漫画のルート自体は削除できません'},
    '｜待翻譯檔案 {0} 張': {'en': ' | Waiting images {0}', 'ja': '｜翻訳待ち画像 {0} 枚'},
    '（{0} 項無法計數）': {'en': ' ({0} jobs uncounted)', 'ja': '（{0} 件は計数できません）'},
    '移除佇列項目': {'en': 'Remove queue items', 'ja': 'キュー項目を削除'},
    '確定移除選取的 {0} 個佇列項目？\n漫畫資料夾與檔案會保留。': {'en': 'Remove the {0} selected queue items?\nComic folders and files will be kept.', 'ja': '選択した {0} 件のキュー項目を削除しますか？\n漫画のフォルダーとファイルは保持されます。'},
    '排序設定': {'en': 'Sort settings', 'ja': '並べ替え設定'},
    '排序欄位': {'en': 'Sort by', 'ja': '並べ替え項目'},
    '排序方向': {'en': 'Order', 'ja': '並べ替え方向'},
    '升冪': {'en': 'Ascending', 'ja': '昇順'},
    '降冪': {'en': 'Descending', 'ja': '降順'},
    '系列名稱': {'en': 'Series name', 'ja': 'シリーズ名'},
    '章節數': {'en': 'Chapter count', 'ja': '章数'},
    '更新時間': {'en': 'Updated', 'ja': '更新日時'},
    '章節維持話數排序，整合編號不變。': {'en': 'Chapters keep their number order and merge indices.', 'ja': '章は話数順のままで、統合番号は変わりません。'},
    '各階段進度': {'en': 'Stage progress', 'ja': '各工程の進捗'},
    '無法讀取 JSON：{0}。請檢查權限與內容，或還原備份後再試；原檔未變更。': {'en': 'Cannot read JSON: {0}. Check permissions and contents, or restore a backup and retry; the original file is unchanged.', 'ja': 'JSON を読み込めません：{0}。権限と内容を確認するか、バックアップを復元して再試行してください。元のファイルは変更されていません。'},
    '累計耗時：{0}': {'en': 'Elapsed: {0}', 'ja': '累計時間：{0}'},
    '總耗時：{0}': {'en': 'Total time: {0}', 'ja': '総時間：{0}'},
    '本次佇列 LLM 消耗（非實際帳單）': {'en': 'LLM usage for this queue run (not a bill)', 'ja': '今回のキューの LLM 使用量（請求額ではありません）'},
    '合計': {'en': 'Total', 'ja': '合計'},
    '累計本次所有資料夾已回報用量；金額依翻譯器估算。': {'en': 'Reported usage across all folders in this queue; cost estimated by the translator.', 'ja': '今回の全フォルダーの報告済み使用量を合計。金額は翻訳ツールの推定です。'},
    '尚未回報': {'en': 'Not reported yet', 'ja': '未報告'},
    '無法預估': {'en': 'Unable to estimate', 'ja': '推定不可'},
    '預估 {0}': {'en': 'Estimated {0}', 'ja': '推定 {0}'},
    '{0} tokens｜{1}｜{2} 次請求': {'en': '{0} tokens | {1} | {2} requests', 'ja': '{0} tokens｜{1}｜{2} リクエスト'},
    '（僅含已知金額）': {'en': ' (known costs only)', 'ja': '（判明した金額のみ）'},
    '（Token 回報不完整）': {'en': ' (incomplete token reports)', 'ja': '（Token 報告が不完全）'},
    '請至少啟用一個 BallonsTranslator 處理階段': {'en': 'Enable at least one BallonsTranslator processing stage', 'ja': 'BallonsTranslator の処理工程を少なくとも一つ有効にしてください'},
    '套用': {'en': 'Apply', 'ja': '適用'},
    '取消': {'en': 'Cancel', 'ja': 'キャンセル'},
    '翻譯頁數': {'en': 'Page range', 'ja': '翻訳ページ'},
    '全部頁面': {'en': 'All pages', 'ja': '全ページ'},
    '最後': {'en': 'last', 'ja': '最後'},
    '第 {0}–{1} 頁': {'en': 'Pages {0}–{1}', 'ja': '{0}～{1} ページ'},
    '起始頁': {'en': 'First page', 'ja': '開始ページ'},
    '結束頁（空白到最後）': {'en': 'Last page (blank = end)', 'ja': '終了ページ（空欄で最後まで）'},
    '共 {0} 頁，依檔名自然排序；包含起訖頁': {'en': '{0} pages in natural filename order; both endpoints included', 'ja': '全 {0} ページ、ファイル名の自然順。開始・終了ページを含む'},
    '翻譯頁數必須介於 1 至 {0}，且起始頁不可大於結束頁': {'en': 'Pages must be between 1 and {0}, with first page no greater than last page', 'ja': '1～{0} の範囲で、開始ページが終了ページ以下になるように指定してください'},
    '指定頁面已完成；全章結果尚未齊全，略過自動匯出與清理': {'en': 'Selected pages completed; chapter results are incomplete, so automatic export and cleanup were skipped', 'ja': '指定ページは完了しました。章全体の結果が未完了のため、自動出力とクリーンアップをスキップしました'},
    '無法開啟結果位置': {'en': 'Cannot open result location', 'ja': '結果の保存場所を開けません'},
    '未啟用': {'en': 'Disabled', 'ja': '無効'},
    '估算中': {'en': 'Estimating', 'ja': '計算中'},
    '{0}%｜{1}/{2} 頁｜剩餘 {3}': {'en': '{0}% | {1}/{2} pages | ETA {3}', 'ja': '{0}%｜{1}/{2} ページ｜残り {3}'},
    '編輯設定檔': {'en': 'Edit configuration', 'ja': '設定ファイルを編集'},
    '編輯 BallonsTranslator 設定檔': {'en': 'Edit BallonsTranslator configuration', 'ja': 'BallonsTranslator 設定ファイルを編集'},
    '請先儲存並關閉設定編輯器': {'en': 'Save and close the configuration editor first', 'ja': '先に設定を保存してエディターを閉じてください'},
    '設定檔含有重複欄位': {'en': 'Configuration contains duplicate fields', 'ja': '設定に重複する項目があります'},
    '數值必須是有限數字': {'en': 'The value must be a finite number', 'ja': '有限の数値を入力してください'},
    '無法讀取 BallonsTranslator 設定定義，請檢查安裝與 Python 路徑': {'en': 'Cannot read BallonsTranslator settings definitions. Check the installation and Python paths.', 'ja': '設定定義を読み取れません。インストール先と Python のパスを確認してください。'},
    'BallonsTranslator 設定工具回傳無效資料': {'en': 'BallonsTranslator settings helper returned invalid data', 'ja': 'BallonsTranslator 設定ツールの応答が無効です'},
    'BallonsTranslator 設定檢查失敗：{0}': {'en': 'BallonsTranslator configuration validation failed: {0}', 'ja': 'BallonsTranslator 設定の検証に失敗しました：{0}'},
    '設定檔根層必須是物件': {'en': 'Configuration root must be an object', 'ja': '設定のルートはオブジェクトである必要があります'},
    '不能移除或取代設定檔根層': {'en': 'Cannot remove or replace the configuration root', 'ja': '設定のルートは削除・置換できません'},
    '欄位型別應為 {0}': {'en': 'Field type must be {0}', 'ja': '項目の型は {0} である必要があります'},
    '設定檔已被其他程式修改，請重新載入後再編輯': {'en': 'Another program changed this file. Reload it before editing.', 'ja': '他のプログラムが設定を変更しました。再読み込みしてから編集してください。'},
    'LLM 配置卡 ID 必須非空白且不可重複': {'en': 'LLM profile IDs must be nonempty and unique', 'ja': 'LLM プロファイル ID は空欄・重複にできません'},
    '選用的 LLM 配置卡不存在：{0}': {'en': 'Selected LLM profile does not exist: {0}', 'ja': '選択された LLM プロファイルが存在しません：{0}'},
    '搜尋設定欄位': {'en': 'Search settings', 'ja': '設定項目を検索'},
    '搜尋': {'en': 'Search', 'ja': '検索'},
    '全部欄位': {'en': 'All fields', 'ja': '全項目'},
    '全部設定': {'en': 'All settings', 'ja': 'すべての設定'},
    '正在讀取設定定義…': {'en': 'Reading settings definitions…', 'ja': '設定定義を読み込み中…'},
    '儲存設定檔': {'en': 'Save configuration', 'ja': '設定を保存'},
    '關閉': {'en': 'Close', 'ja': '閉じる'},
    '重新載入': {'en': 'Reload', 'ja': '再読み込み'},
    '設定欄位': {'en': 'Setting', 'ja': '設定項目'},
    '目前值': {'en': 'Current value', 'ja': '現在の値'},
    '操作失敗，原設定檔未被取代': {'en': 'Operation failed; the original configuration was not replaced', 'ja': '操作に失敗しました。元の設定ファイルは保持されています'},
    '已設定（遮蔽）': {'en': 'Set (hidden)', 'ja': '設定済み（非表示）'},
    '{0} 個欄位／項目': {'en': '{0} fields/items', 'ja': '{0} 項目'},
    '{0} 個可見欄位；{1}': {'en': '{0} visible fields; {1}', 'ja': '{0} 件の表示項目；{1}'},
    '尚未儲存': {'en': 'Unsaved changes', 'ja': '未保存の変更あり'},
    '設定已載入': {'en': 'Configuration loaded', 'ja': '設定を読み込みました'},
    '金鑰留白會保留原值；輸入新值可取代。': {'en': 'Leave blank to keep the saved key; enter a new key to replace it.', 'ja': '空欄のままで保存済みのキーを保持します。新しいキーを入力すると置換します。'},
    '清除已保存的金鑰': {'en': 'Clear the saved key', 'ja': '保存済みのキーを消去'},
    '展開左側項目即可編輯每個欄位。': {'en': 'Expand items on the left to edit each field.', 'ja': '左側の項目を展開して各設定を編集できます。'},
    '新增欄位／項目': {'en': 'Add field/item', 'ja': '項目を追加'},
    '加入／套用範本': {'en': 'Add/apply template', 'ja': 'テンプレートを追加・適用'},
    '啟用': {'en': 'Enabled', 'ja': '有効'},
    '選擇檔案': {'en': 'Choose file', 'ja': 'ファイルを選択'},
    '選擇資料夾': {'en': 'Choose folder', 'ja': 'フォルダーを選択'},
    '使用空值（null）': {'en': 'Use null', 'ja': '空値（null）を使用'},
    '型別：{0}': {'en': 'Type: {0}', 'ja': '型：{0}'},
    '套用欄位': {'en': 'Apply field', 'ja': '項目を適用'},
    '移除欄位／項目': {'en': 'Remove field/item', 'ja': '項目を削除'},
    '複製項目': {'en': 'Duplicate item', 'ja': '項目を複製'},
    '欄位值無效，請檢查型別與數值': {'en': 'Invalid field value. Check its type and number format.', 'ja': '項目の値が無効です。型と数値を確認してください。'},
    '新 LLM 配置卡': {'en': 'New LLM profile', 'ja': '新しい LLM プロファイル'},
    '以範本取代此物件？尚未儲存前可以重新載入還原。': {'en': 'Replace this object with the template? Reload to undo unsaved changes.', 'ja': 'このオブジェクトをテンプレートで置換しますか？保存前なら再読み込みで元に戻せます。'},
    '欄位名稱': {'en': 'Field name', 'ja': '項目名'},
    '欄位型別': {'en': 'Field type', 'ja': '項目の型'},
    '欄位已存在': {'en': 'Field already exists', 'ja': '項目はすでに存在します'},
    '移除此欄位或項目？變更會在儲存後生效。': {'en': 'Remove this field or item? Changes take effect after saving.', 'ja': 'この項目を削除しますか？変更は保存後に反映されます。'},
    '正在檢查並儲存設定…': {'en': 'Validating and saving settings…', 'ja': '設定を検証・保存中…'},
    '已儲存；備份：{0}': {'en': 'Saved; backup: {0}', 'ja': '保存しました；バックアップ：{0}'},
    '沒有變更': {'en': 'No changes', 'ja': '変更なし'},
    '放棄未儲存的變更並重新載入？': {'en': 'Discard unsaved changes and reload?', 'ja': '未保存の変更を破棄して再読み込みしますか？'},
    '是否儲存設定變更？': {'en': 'Save configuration changes?', 'ja': '設定の変更を保存しますか？'},
    '此值由偵測、OCR、翻譯與修補開關自動計算。': {'en': 'Calculated from detection, OCR, translation and inpainting switches.', 'ja': '検出・OCR・翻訳・修復のスイッチから自動計算されます。'},
    '舊版相容欄位；請展開「文字特效」修改對應設定。': {'en': 'Legacy compatibility field. Edit the corresponding setting under Text effects.', 'ja': '旧版互換用の項目です。「文字効果」で対応する設定を編集してください。'},
    '請選擇支援的選項': {'en': 'Choose a supported option', 'ja': '対応する選択肢を選んでください'},
    '數值超出允許範圍': {'en': 'Number is outside the allowed range', 'ja': '数値が許容範囲外です'},
    '文字': {'en': 'Text', 'ja': '文字列'},
    '整數': {'en': 'Integer', 'ja': '整数'},
    '小數': {'en': 'Decimal', 'ja': '小数'},
    '布林值': {'en': 'Boolean', 'ja': '真偽値'},
    '物件': {'en': 'Object', 'ja': 'オブジェクト'},
    '清單': {'en': 'List', 'ja': 'リスト'},
    '空值': {'en': 'Null', 'ja': '空値'},
    '自動化模組': {'en': 'Automation modules', 'ja': '自動化モジュール'},
    'LLM 配置卡': {'en': 'LLM profiles', 'ja': 'LLM プロファイル'},
    '字體與排版': {'en': 'Font and layout', 'ja': 'フォントとレイアウト'},
    '繪圖工具': {'en': 'Drawing tools', 'ja': '描画ツール'},
    '套件管理': {'en': 'Package manager', 'ja': 'パッケージ管理'},
    '下載鏡像': {'en': 'Download mirrors', 'ja': 'ダウンロードミラー'},
    '自動縱中橫': {'en': 'Automatic tate-chu-yoko', 'ja': '自動縦中横'},
    '文字偵測器': {'en': 'Text detector', 'ja': '文字検出器'},
    '翻譯器': {'en': 'Translator', 'ja': '翻訳器'},
    '修補器': {'en': 'Inpainter', 'ja': '修復器'},
    '偵測器參數': {'en': 'Detector parameters', 'ja': '検出器のパラメーター'},
    'OCR 參數': {'en': 'OCR parameters', 'ja': 'OCR パラメーター'},
    '翻譯器參數': {'en': 'Translator parameters', 'ja': '翻訳器のパラメーター'},
    '修補器參數': {'en': 'Inpainter parameters', 'ja': '修復器のパラメーター'},
    '啟用文字偵測': {'en': 'Enable text detection', 'ja': '文字検出を有効化'},
    '啟用 OCR': {'en': 'Enable OCR', 'ja': 'OCR を有効化'},
    '啟用翻譯': {'en': 'Enable translation', 'ja': '翻訳を有効化'},
    '啟用修補': {'en': 'Enable inpainting', 'ja': '修復を有効化'},
    '來源語言': {'en': 'Source language', 'ja': '原文の言語'},
    '目標語言': {'en': 'Target language', 'ja': '翻訳先の言語'},
    '翻譯分組': {'en': 'Translation grouping', 'ja': '翻訳の単位'},
    'LLM 上下文': {'en': 'LLM context', 'ja': 'LLM コンテキスト'},
    '上下文 Token 預算': {'en': 'Context token budget', 'ja': 'コンテキストのトークン予算'},
    '術語表路徑': {'en': 'Glossary path', 'ja': '用語集のパス'},
    '術語表模式': {'en': 'Glossary mode', 'ja': '用語集モード'},
    '翻譯使用圖片': {'en': 'Use images for translation', 'ja': '翻訳に画像を使用'},
    '摘要與記憶': {'en': 'Summary and memory', 'ja': '要約とメモリー'},
    '覆寫既有摘要': {'en': 'Overwrite existing summaries', 'ja': '既存の要約を上書き'},
    '翻譯用 LLM': {'en': 'Translation LLM', 'ja': '翻訳用 LLM'},
    'OCR 用 LLM': {'en': 'OCR LLM', 'ja': 'OCR 用 LLM'},
    '修補用 LLM': {'en': 'Inpainting LLM', 'ja': '修復用 LLM'},
    'API 金鑰': {'en': 'API key', 'ja': 'API キー'},
    '基礎 URL': {'en': 'Base URL', 'ja': 'ベース URL'},
    '文本模型': {'en': 'Text model', 'ja': 'テキストモデル'},
    '視覺模型': {'en': 'Vision model', 'ja': '視覚モデル'},
    '圖像模型': {'en': 'Image model', 'ja': '画像モデル'},
    'Token 輸出上限': {'en': 'Output token limit', 'ja': '出力トークン上限'},
    '溫度': {'en': 'Temperature', 'ja': '温度'},
    '頻率懲罰': {'en': 'Frequency penalty', 'ja': '頻度ペナルティ'},
    '存在懲罰': {'en': 'Presence penalty', 'ja': '存在ペナルティ'},
    '思考級別': {'en': 'Thinking level', 'ja': '思考レベル'},
    '翻譯提示詞': {'en': 'Translation prompt', 'ja': '翻訳プロンプト'},
    '視覺提示詞': {'en': 'Vision prompt', 'ja': '視覚プロンプト'},
    '圖像提示詞': {'en': 'Image prompt', 'ja': '画像プロンプト'},
    '返回 JSON Schema': {'en': 'Return JSON Schema', 'ja': 'JSON Schema 応答'},
    '需要 API 金鑰': {'en': 'API key required', 'ja': 'API キーが必要'},
    '支援文本': {'en': 'Text support', 'ja': 'テキスト対応'},
    '支援視覺': {'en': 'Vision support', 'ja': '視覚対応'},
    '支援圖像': {'en': 'Image support', 'ja': '画像対応'},
    '字體': {'en': 'Font family', 'ja': 'フォント'},
    '字體大小': {'en': 'Font size', 'ja': 'フォントサイズ'},
    '直排': {'en': 'Vertical writing', 'ja': '縦書き'},
    '對齊': {'en': 'Alignment', 'ja': '配置'},
    '行距': {'en': 'Line spacing', 'ja': '行間'},
    '字距': {'en': 'Letter spacing', 'ja': '字間'},
    '文字特效': {'en': 'Text effects', 'ja': '文字効果'},
    '文字變形': {'en': 'Text transforms', 'ja': '文字の変形'},
    '結果圖片格式': {'en': 'Result image format', 'ja': '結果画像の形式'},
    '圖片品質': {'en': 'Image quality', 'ja': '画像品質'},
    '中間圖片格式': {'en': 'Intermediate image format', 'ja': '中間画像の形式'},
    '顯示語言': {'en': 'Display language', 'ja': '表示言語'},
    '深色模式': {'en': 'Dark mode', 'ja': 'ダークモード'},
    'OCR 取代規則': {'en': 'OCR replacements', 'ja': 'OCR 置換ルール'},
    '翻譯前取代規則': {'en': 'Pre-translation replacements', 'ja': '翻訳前の置換ルール'},
    '翻譯後取代規則': {'en': 'Post-translation replacements', 'ja': '翻訳後の置換ルール'},
    '拼寫檢查': {'en': 'Spell checking', 'ja': 'スペルチェック'},
    '流程模式': {'en': 'Pipeline mode', 'ja': '処理モード'},
    '樣式檔路徑': {'en': 'Style file path', 'ja': 'スタイルファイルのパス'},
    '開啟紀錄資料夾': {'en': 'Open log folder', 'ja': 'ログフォルダーを開く'},
    '；紀錄：{0}': {'en': '; Log: {0}', 'ja': '；ログ：{0}'},
    '部分翻譯': {'en': 'Partially translated', 'ja': '翻訳未完了'},
    '{0} 張翻譯圖片｜部分翻譯': {'en': '{0} translated images | Incomplete', 'ja': '翻訳画像 {0} 枚｜翻訳未完了'},
    '清除搜尋': {'en': 'Clear search', 'ja': '検索をクリア'},
    '上次執行中斷，請確認結果後重試': {'en': 'The previous run was interrupted. Check its results before retrying.', 'ja': '前回の実行が中断されました。結果を確認してから再試行してください。'},
    '來源沒有可整合的圖片：{0}': {'en': 'Source has no images to merge: {0}', 'ja': '結合できる画像が元フォルダーにありません：{0}'},
    '章節範圍重疊或順序錯誤：{0}。請只選擇不重疊的來源章節。': {'en': 'Chapter ranges overlap or are out of order: {0}. Select only non-overlapping source chapters.', 'ja': '章の範囲が重複しているか順序が不正です：{0}。重複しない元の章のみ選択してください。'},
    '輸出已屬於其他來源，請改用不同的 Komga 路徑或系列名稱：{0}': {'en': 'Output belongs to another source. Use a different Komga path or series name: {0}', 'ja': '出力は別の元フォルダーに属しています。Komga の出力先またはシリーズ名を変更してください：{0}'},
    '\n\n既有輸出將被取代（包含其中的翻譯結果）：{0}': {'en': '\n\nExisting output will be replaced, including its translations: {0}', 'ja': '\n\n既存の出力は翻訳結果を含めて置き換えられます：{0}'},
    '\n\n注意：整合成功後，將永久刪除本次範圍內除最後一個之外的來源資料夾與內容。\n保留：{0}': {'en': '\n\nWarning: After a successful merge, all source folders and their contents in this range except the last folder will be permanently deleted.\nKeep: {0}', 'ja': '\n\n注意：結合が成功すると、今回の範囲内の最後のフォルダーを除くすべての元フォルダーとその内容が完全に削除されます。\n保持：{0}'},
    '\n已清除 {0} 個來源資料夾': {'en': '\nRemoved {0} source folders', 'ja': '\n元フォルダーを {0} 個削除しました'},
    '  清理：{0} 個資料夾／{1} 個項目': {'en': '  Cleanup: {0} folders / {1} items', 'ja': '  クリーンアップ：{0} 個のフォルダー／{1} 個の項目'},
    'BallonsTranslator 佇列': {'en': 'BallonsTranslator queue', 'ja': 'BallonsTranslator キュー'},
    'BallonsTranslator 未成功完成（exit={0}）；請查看其 logs': {'en': 'BallonsTranslator did not complete successfully (exit={0}); check its logs', 'ja': 'BallonsTranslator が正常に完了しませんでした（exit={0}）。ログを確認してください'},
    'BallonsTranslator 的 --exec_dirs 不支援含逗號的路徑': {'en': 'BallonsTranslator --exec_dirs does not support paths containing commas', 'ja': 'BallonsTranslator の --exec_dirs はカンマを含むパスに対応していません'},
    'BallonsTranslator：待命': {'en': 'BallonsTranslator: Standby', 'ja': 'BallonsTranslator：待機中'},
    'CBZ 內容損壞': {'en': 'Corrupted CBZ contents', 'ja': 'CBZ の内容が破損しています'},
    'CBZ 含有子資料夾或非圖片檔案': {'en': 'CBZ contains subfolders or non-image files', 'ja': 'CBZ にサブフォルダーまたは画像以外のファイルが含まれています'},
    'CBZ 圖片數量、順序或名稱不符': {'en': 'CBZ image count, order, or names do not match', 'ja': 'CBZ の画像数、順序、または名前が一致しません'},
    'Comic sorting 錯誤': {'en': 'Comic sorting error', 'ja': 'Comic sorting エラー'},
    'Komga 匯出': {'en': 'Komga export', 'ja': 'Komga エクスポート'},
    'Komga 匯出完成': {'en': 'Komga export complete', 'ja': 'Komga エクスポートが完了しました'},
    'Komga 匯出完成（含錯誤）': {'en': 'Komga export complete with errors', 'ja': 'Komga エクスポートが完了しました（一部エラーあり）'},
    'Komga 輸出路徑不能位於漫畫來源路徑內': {'en': 'Komga output path cannot be inside the comic source path', 'ja': 'Komga の出力先を漫画の元フォルダー内に指定することはできません'},
    'Komga 輸出路徑：': {'en': 'Komga output path:', 'ja': 'Komga 出力先：'},
    'Python（空白使用內附環境）': {'en': 'Python (blank = bundled)', 'ja': 'Python（空欄＝同梱環境）'},
    '{0}\n…共 {1} 個章節': {'en': '{0}\n…{1} chapters in total', 'ja': '{0}\n…全 {1} 章'},
    '{0} 個章節': {'en': '{0} chapters', 'ja': '{0} 章'},
    '{0} 個系列，{1} 個章節': {'en': '{0} series, {1} chapters', 'ja': '{0} シリーズ、{1} 章'},
    '{0} 張圖片｜未翻譯': {'en': '{0} images | Untranslated', 'ja': '画像 {0} 枚｜未翻訳'},
    '{0} 張翻譯圖片｜可匯出': {'en': '{0} translated images | Ready to export', 'ja': '翻訳済み画像 {0} 枚｜エクスポート可能'},
    '{0}: 不清理符號連結': {'en': '{0}: Skipping symlink cleanup', 'ja': '{0}：シンボリックリンクは削除しません'},
    '整合＋加入佇列': {'en': 'Merge + enqueue', 'ja': '結合＋キューに追加'},
    '整合完成，已加入佇列，等待手動開始': {'en': 'Merge complete; queued, waiting for manual start', 'ja': '結合完了。キューに追加し、手動開始を待機中'},
    '不允許刪除系列目錄外或符號連結資料夾': {'en': 'Cannot delete folders outside the series directory or symlink folders', 'ja': 'シリーズのディレクトリ外にあるフォルダーやシンボリックリンクのフォルダーは削除できません'},
    '主佇列進度': {'en': 'Main queue progress', 'ja': 'メインキューの進行状況'},
    '佇列將清空指定路徑的 mask / inpainted 內容，無法復原。繼續？': {'en': 'The queue will clear mask / inpainted contents at the specified paths. This cannot be undone. Continue?', 'ja': 'キューは指定パスの mask / inpainted の内容を削除します。この操作は元に戻せません。続行しますか？'},
    '佇列已停止': {'en': 'Queue stopped', 'ja': 'キューを停止しました'},
    '佇列結束，請查看各項狀態': {'en': 'Queue finished. Check the status of each item', 'ja': 'キューの処理が終了しました。各項目の状態を確認してください'},
    '佇列設定': {'en': 'Queue settings', 'ja': 'キュー設定'},
    '來源不是資料夾': {'en': 'Source is not a folder', 'ja': '元のパスがフォルダーではありません'},
    '來源清理失敗': {'en': 'Source cleanup failed', 'ja': '元フォルダーの削除に失敗しました'},
    '停止': {'en': 'Stop', 'ja': '停止'},
    '加入上方選取項目': {'en': 'Add items selected above', 'ja': '上で選択した項目を追加'},
    '加入指定路徑': {'en': 'Add path', 'ja': 'パスを指定して追加'},
    '動作': {'en': 'Action', 'ja': '操作'},
    '匯出': {'en': 'Export', 'ja': 'エクスポート'},
    '指定頁面完成後匯出 CBZ': {'en': 'Export CBZ after the selected pages finish', 'ja': '指定ページの完了後に CBZ をエクスポート'},
    '指定頁數專用，預設不匯出；勾選後須全章結果齊全才匯出整章 CBZ。': {'en': 'Selected pages only; export is off by default. When enabled, export the whole chapter only if all results are available.', 'ja': '指定ページ専用。既定ではエクスポートしません。有効にすると、全ページの結果が揃った場合に章全体を CBZ に出力します。'},
    '匯出完成後開啟輸出資料夾': {'en': 'Open output folder after export', 'ja': 'エクスポート後に出力フォルダーを開く'},
    '匯出所有已翻譯項目': {'en': 'Export all translated items', 'ja': '翻訳済みの全項目をエクスポート'},
    '匯出與漫畫路徑不可互相包含': {'en': 'Export and comic paths cannot contain each other', 'ja': '出力先と漫画のパスを互いの配下に指定することはできません'},
    '匯出選取項目': {'en': 'Export selected items', 'ja': '選択項目をエクスポート'},
    '可匯出': {'en': 'Ready to export', 'ja': 'エクスポート可能'},
    '執行中': {'en': 'Running', 'ja': '実行中'},
    '失敗': {'en': 'Failed', 'ja': '失敗'},
    '失敗：{0}': {'en': 'Failed: {0}', 'ja': '失敗：{0}'},
    '安裝路徑': {'en': 'Installation path', 'ja': 'インストール先'},
    '完成': {'en': 'Complete', 'ja': '完了'},
    '完成（有異常）': {'en': 'Complete (with anomalies)', 'ja': '完了（異常あり）'},
    '流程已完成但發現異常（exit={0}）': {'en': 'Processing completed with anomalies (exit={0})', 'ja': '処理は完了しましたが異常があります（exit={0}）'},
    '將清空目前漫畫路徑下所有 mask 與 inpainted 資料夾內容。\n資料夾本身會保留，此操作無法復原。確定繼續嗎？': {'en': 'This will clear all mask and inpainted folder contents under the current comic path.\nThe folders themselves will be kept. This cannot be undone. Continue?', 'ja': '現在の漫画パス内にあるすべての mask と inpainted フォルダーの内容を削除します。\nフォルダー自体は残ります。この操作は元に戻せません。続行しますか？'},
    '尚未掃描': {'en': 'Not scanned yet', 'ja': '未スキャン'},
    '就緒': {'en': 'Ready', 'ja': '準備完了'},
    '工作執行中': {'en': 'Task running', 'ja': 'タスク実行中'},
    '已停止': {'en': 'Stopped', 'ja': '停止しました'},
    '已停止，未執行後續清理': {'en': 'Stopped; subsequent cleanup was not performed', 'ja': '停止しました。後続のクリーンアップは実行されていません'},
    '已停止；未執行此項目的後續動作': {'en': 'Stopped; subsequent actions for this item were not performed', 'ja': '停止しました。この項目の後続処理は実行されていません'},
    '已存在且來源未變更時跳過': {'en': 'Skip existing items if the source is unchanged', 'ja': '元データに変更がない既存項目をスキップ'},
    '已清理 {0} 個資料夾、移除 {1} 個項目': {'en': 'Cleaned {0} folders and removed {1} items', 'ja': '{0} 個のフォルダーをクリーンアップし、{1} 個の項目を削除しました'},
    '序號｜系列 / 章節': {'en': 'No. | Series / Chapter', 'ja': '番号｜シリーズ／章'},
    '您確定要整合以下資料夾嗎？\n\n{0}': {'en': 'Merge the following folders?\n\n{0}', 'ja': '次のフォルダーを結合しますか？\n\n{0}'},
    '成功後清理 mask / inpainted': {'en': 'Clean up mask / inpainted on success', 'ja': '成功後に mask / inpainted をクリーンアップ'},
    '指定路徑沒有圖片，請選擇章節或整合輸出': {'en': 'No images at the specified path. Select a chapter or merge output', 'ja': '指定パスに画像がありません。章または結合結果を選択してください'},
    '掃描失敗': {'en': 'Scan failed', 'ja': 'スキャンに失敗しました'},
    '整合失敗': {'en': 'Merge failed', 'ja': '結合に失敗しました'},
    '整合完成（清理含錯誤）': {'en': 'Merge complete with cleanup errors', 'ja': '結合が完了しました（クリーンアップでエラーあり）'},
    '整合後清除來源': {'en': 'Delete sources after merging', 'ja': '結合後に元フォルダーを削除'},
    '保留最後一個': {'en': 'Keep last source', 'ja': '最後の元フォルダーを保持'},
    '\n\n注意：整合成功後，將永久刪除本次範圍內的所有來源資料夾與內容（整合輸出除外）。': {'en': '\n\nWarning: After a successful merge, all source folders and their contents in this range will be permanently deleted, except the merged output.', 'ja': '\n\n注意：結合が成功すると、今回の範囲内のすべての元フォルダーとその内容が完全に削除されます（結合出力を除く）。'},
    '新增': {'en': 'New', 'ja': '新規'},
    '新增：{0}  更新：{1}  跳過：{2}  失敗：{3}': {'en': 'New: {0}  Updated: {1}  Skipped: {2}  Failed: {3}', 'ja': '新規：{0}  更新：{1}  スキップ：{2}  失敗：{3}'},
    '更新': {'en': 'Update', 'ja': '更新'},
    '更新時間 ↓': {'en': 'Modified ↓', 'ja': '更新日時 ↓'},
    '未翻譯': {'en': 'Untranslated', 'ja': '未翻訳'},
    '檔案已重命名並複製到 {0}': {'en': 'Files renamed and copied to {0}', 'ja': 'ファイル名を変更し、{0} にコピーしました'},
    '正在掃描…': {'en': 'Scanning…', 'ja': 'スキャン中…'},
    '正在整合… {0} / {1}': {'en': 'Merging… {0} / {1}', 'ja': '結合中… {0} / {1}'},
    '正在清理 mask / inpainted…': {'en': 'Cleaning up mask / inpainted…', 'ja': 'mask / inpainted をクリーンアップ中…'},
    '正在處理：{0}': {'en': 'Processing: {0}', 'ja': '処理中：{0}'},
    '正在處理：{0} — {1} / {2}': {'en': 'Processing: {0} — {1} / {2}', 'ja': '処理中：{0} — {1} / {2}'},
    '此路徑前置工作失敗，跳過後續動作': {'en': 'A prerequisite task failed for this path; skipping subsequent actions', 'ja': 'このパスの前段階の処理に失敗したため、後続処理をスキップします'},
    '沒有可匯出的翻譯結果': {'en': 'No translated results available to export', 'ja': 'エクスポート可能な翻訳結果がありません'},
    '清理': {'en': 'Cleanup', 'ja': 'クリーンアップ'},
    '清理失敗': {'en': 'Cleanup failed', 'ja': 'クリーンアップに失敗しました'},
    '清理失敗：{0}': {'en': 'Cleanup failed: {0}', 'ja': 'クリーンアップに失敗しました：{0}'},
    '清理完成': {'en': 'Cleanup complete', 'ja': 'クリーンアップが完了しました'},
    '清理完成（含錯誤）': {'en': 'Cleanup complete with errors', 'ja': 'クリーンアップが完了しました（一部エラーあり）'},
    '清理所有 mask / inpainted': {'en': 'Clean up all mask / inpainted folders', 'ja': 'すべての mask / inpainted をクリーンアップ'},
    '準備匯出…': {'en': 'Preparing export…', 'ja': 'エクスポートを準備中…'},
    '準備整合…': {'en': 'Preparing merge…', 'ja': '結合を準備中…'},
    '漫畫整合': {'en': 'Comic merge', 'ja': '漫画の結合'},
    '漫畫整合工具': {'en': 'Comic merge tool', 'ja': '漫画結合ツール'},
    '漫畫路徑': {'en': 'Comic path', 'ja': '漫画パス'},
    '漫畫路徑不存在': {'en': 'Comic path does not exist', 'ja': '漫画パスが存在しません'},
    '漫畫路徑：': {'en': 'Comic path:', 'ja': '漫画パス：'},
    '瀏覽': {'en': 'Browse', 'ja': '参照'},
    '無法寫入 EXE 同目錄的設定檔：\n{0}\n\n{1}': {'en': 'Cannot write the settings file in the EXE directory:\n{0}\n\n{1}', 'ja': 'EXE と同じディレクトリに設定ファイルを書き込めません：\n{0}\n\n{1}'},
    '狀態': {'en': 'Status', 'ja': '状態'},
    '狀態檔: {0}': {'en': 'Status file: {0}', 'ja': '状態ファイル：{0}'},
    '確認整合': {'en': 'Confirm merge', 'ja': '結合の確認'},
    '確認清理': {'en': 'Confirm cleanup', 'ja': 'クリーンアップの確認'},
    '移除選取': {'en': 'Remove selected', 'ja': '選択項目を削除'},
    '等待': {'en': 'Waiting', 'ja': '待機中'},
    '結束編號：': {'en': 'End number:', 'ja': '終了番号：'},
    '結果為空': {'en': 'Empty result', 'ja': '結果が空です'},
    '結果資料夾為空': {'en': 'Result folder is empty', 'ja': '結果フォルダーが空です'},
    '翻譯': {'en': 'Translate', 'ja': '翻訳'},
    '翻譯成功後匯出 CBZ': {'en': 'Export CBZ after successful translation', 'ja': '翻訳成功後に CBZ をエクスポート'},
    '翻譯結果不完整，未執行後續動作': {'en': 'Translation results are incomplete; subsequent actions were not performed', 'ja': '翻訳結果が不完全なため、後続処理は実行されていません'},
    '設定保存失敗': {'en': 'Failed to save settings', 'ja': '設定の保存に失敗しました'},
    '請先在 BallonsTranslator 儲存設定並關閉原生介面': {'en': 'Save settings in BallonsTranslator and close its interface first', 'ja': '先に BallonsTranslator で設定を保存し、その画面を閉じてください'},
    '請先選擇父系列或章節': {'en': 'Select a parent series or chapter first', 'ja': '先に親シリーズまたは章を選択してください'},
    '請確保編號範圍有效': {'en': 'Make sure the number range is valid', 'ja': '番号の範囲が正しいか確認してください'},
    '請確認漫畫與 Komga 路徑': {'en': 'Check the comic and Komga paths', 'ja': '漫画と Komga のパスを確認してください'},
    '請等待目前工作完成，或先停止翻譯佇列。': {'en': 'Wait for the current task to finish, or stop the translation queue first.', 'ja': '現在のタスクが完了するまで待つか、先に翻訳キューを停止してください。'},
    '請設定 Komga 輸出路徑': {'en': 'Set the Komga output path', 'ja': 'Komga の出力先を設定してください'},
    '請設定有效的 BallonsTranslator 安裝目錄及其 Python 執行檔': {'en': 'Set a valid BallonsTranslator installation directory and its Python executable', 'ja': '有効な BallonsTranslator のインストール先と、その Python 実行ファイルを設定してください'},
    '請輸入有效的起始和結束編號': {'en': 'Enter valid start and end numbers', 'ja': '有効な開始番号と終了番号を入力してください'},
    '請選擇既有 BallonsTranslator config JSON': {'en': 'Select an existing BallonsTranslator config JSON', 'ja': '既存の BallonsTranslator 設定 JSON を選択してください'},
    '請選擇有效的漫畫路徑': {'en': 'Select a valid comic path', 'ja': '有効な漫画パスを選択してください'},
    '警告': {'en': 'Warning', 'ja': '警告'},
    '資料夾大小': {'en': 'Folder size', 'ja': 'フォルダーサイズ'},
    '起始編號：': {'en': 'Start number:', 'ja': '開始番号：'},
    '跳過': {'en': 'Skip', 'ja': 'スキップ'},
    '輸出路徑不是資料夾：{0}': {'en': 'Output path is not a folder: {0}', 'ja': '出力先がフォルダーではありません：{0}'},
    '選取範圍沒有可整合的圖片': {'en': 'No images to merge in the selected range', 'ja': '選択範囲に結合可能な画像がありません'},
    '選取項目沒有可匯出的翻譯結果': {'en': 'No translated results to export in the selected items', 'ja': '選択項目にエクスポート可能な翻訳結果がありません'},
    '重新掃描': {'en': 'Rescan', 'ja': '再スキャン'},
    '開啟原生設定介面': {'en': 'Open native settings interface', 'ja': '本体の設定画面を開く'},
    '開始主佇列': {'en': 'Start main queue', 'ja': 'メインキューを開始'},
    '重新啟動後套用語言': {'en': 'Language changes take effect after restart', 'ja': '言語の変更は再起動後に適用されます'},
    '設定檔': {'en': 'Config file', 'ja': '設定ファイル'},
    'Text Detection': {'zh-TW': '文字偵測', 'en': 'Text Detection', 'ja': '文字検出'},
    'OCR': {'zh-TW': 'OCR', 'en': 'OCR', 'ja': 'OCR'},
    'Translation': {'zh-TW': '翻譯', 'en': 'Translation', 'ja': '翻訳'},
    'Inpaint': {'zh-TW': '修補', 'en': 'Inpaint', 'ja': '画像修復'},
}

TRANSLATIONS.update({
    "搜尋系列／章節": {"en": "Search series / chapters", "ja": "シリーズ／章を検索"},
    "已選取 {0} 個章節": {"en": "{0} chapters selected", "ja": "{0} 章を選択中"},
    "主佇列": {"en": "Queue", "ja": "キュー"},
    "設定": {"en": "Settings", "ja": "設定"},
    "整合時請只選擇同一系列的章節": {"en": "Select chapters from one series to merge", "ja": "結合する章は同じシリーズから選択してください"},
    "前置工作失敗": {"en": "Blocked", "ja": "前の処理が失敗"},
    "上移": {"en": "Move up", "ja": "上へ"},
    "下移": {"en": "Move down", "ja": "下へ"},
    "重試選取": {"en": "Retry selected", "ja": "選択項目を再試行"},
    "清除已完成": {"en": "Clear completed", "ja": "完了項目を除去"},
    "工作詳情": {"en": "Job details", "ja": "処理の詳細"},
    "佇列 {0} 項｜等待 {1}｜完成 {2}｜需處理 {3}": {"en": "Queue: {0} | Pending: {1} | Done: {2} | Needs attention: {3}", "ja": "キュー {0} 件｜待機 {1}｜完了 {2}｜要確認 {3}"},
    "不支援的佇列動作：{0}": {"en": "Unsupported queue action: {0}", "ja": "未対応のキュー操作：{0}"},
    "請先重試此路徑的失敗工作：{0}": {"en": "Retry the failed job for this path first: {0}", "ja": "このパスで失敗した処理を先に再試行してください：{0}"},
})
